### ISSUE TITLE
Package docker-ce is not available error Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by ronna** [medic/cht-infrastructure#9]
Ubuntu does not have the docker repo out of the box  and running the prepare.sh script throws the below error:

Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Unable to locate package docker-ce-cli
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'

Official docker Ubuntu Installation docs:
https://docs.docker.com/engine/install/ubuntu/

**Comment by nomulex** [comment]
[Support for this](https://download.docker.com/linux/debian/dists/bullseye/) was added in June 2021.

**Comment by mrjones-plip** [comment]
@nomulex  - was there a plan to use the debian repo you cited in ubuntu?  This otherwise still failed for me:

```
root@deleteme:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

root@deleteme:~# sudo apt-get update
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done


root@deleteme:~# sudo apt-get install -y docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Unable to locate package docker-ce-cli
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
```

**Comment by nomulex** [comment]
Maybe you are pointed to a repo that has not been updated. It works for me as shown below and docker also says it should work [here](https://docs.docker.com/engine/install/ubuntu/#os-requirements). 
```bash
root@cht:/home/chtadmin# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
root@cht:/home/chtadmin# sudo apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
containerd.io is already the newest version (1.4.6-1).
docker-ce-cli is already the newest version (5:20.10.7~3-0~ubuntu-focal).
docker-ce is already the newest version (5:20.10.7~3-0~ubuntu-focal).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
root@cht:/home/chtadmin# 
```

**Comment by mrjones-plip** [comment]
Hmmm - I'm still not seeing it show up when testing on another box.  As well, that docker.com page you linked to says you should [add their repo](https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository) to get it to work.  However, this is more SRE stuffs and I was more just curious. If y'all are happy with the state of things, I don't have any concerns!  :rocket:

**Comment by nomulex** [comment]
Adding here that if you miss step 3 of the steps described [here](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository). You get that error. To overcome it you need to run the below command to set up the stable repository. 

```

echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null


```

**Comment by mrjones-plip** [comment]
@nomulex - Sweet! Good point.  

Sounds like we both agree then:  The fact that it was added to Debian repo you cited doesn't affect Ubuntu 20.04 installs as you still need to add the `docker.com` apt repo for the [`prepare.sh`](https://github.com/medic/cht-infrastructure/blob/master/self-hosting/prepare-system/ubuntu/prepare.sh) script to work.

**Comment by mrjones-plip** [comment]
Ohhh!!! You see that too as you fixed the `prepare.sh` script [with this PR](https://github.com/medic/cht-infrastructure/pull/14/files) - \o/

I <3 SRE

**Comment by amici** [comment]
> 
> Adding here that if you miss step 3 of the steps described [here](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository). You get that error. To overcome it you need to run the below command to set up the stable repository.
 
Also, I've got the same error when I missed the step `sudo apt-get update`, **after** adding the stable repository, and just before actually trying to install the docker engine.
